[2023-07-30T21:15:58.556+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loading_dag.execute_sql_script_task scheduled__2023-07-29T00:00:00+00:00 [queued]>
[2023-07-30T21:15:58.562+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loading_dag.execute_sql_script_task scheduled__2023-07-29T00:00:00+00:00 [queued]>
[2023-07-30T21:15:58.563+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-30T21:15:58.575+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): execute_sql_script_task> on 2023-07-29 00:00:00+00:00
[2023-07-30T21:15:58.580+0300] {standard_task_runner.py:57} INFO - Started process 35053 to run task
[2023-07-30T21:15:58.587+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'data_loading_dag', 'execute_sql_script_task', 'scheduled__2023-07-29T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dataDAG.py', '--cfg-path', '/var/folders/5c/9q48lshd61z8kg1c11xx5g4c0000gn/T/tmp0uud3se3']
[2023-07-30T21:15:58.589+0300] {standard_task_runner.py:85} INFO - Job 3: Subtask execute_sql_script_task
[2023-07-30T21:15:58.641+0300] {task_command.py:410} INFO - Running <TaskInstance: data_loading_dag.execute_sql_script_task scheduled__2023-07-29T00:00:00+00:00 [running]> on host macbook-pro-olga.local
[2023-07-30T21:15:58.705+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_loading_dag' AIRFLOW_CTX_TASK_ID='execute_sql_script_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-29T00:00:00+00:00'
[2023-07-30T21:15:58.745+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/olgastash/neoflex_env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/Users/olgastash/neoflex_env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/olgastash/airflow/dags/dataDAG.py", line 24, in execute_sql_script
    conn = connect_to_database()
  File "/Users/olgastash/airflow/dags/dataDAG.py", line 12, in connect_to_database
    conn = psycopg2.connect(
  File "/Users/olgastash/neoflex_env_airflow/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  database "Airflow.public" does not exist

[2023-07-30T21:15:58.753+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=data_loading_dag, task_id=execute_sql_script_task, execution_date=20230729T000000, start_date=20230730T181558, end_date=20230730T181558
[2023-07-30T21:15:58.762+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task execute_sql_script_task (connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  database "Airflow.public" does not exist
; 35053)
[2023-07-30T21:15:58.811+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-30T21:15:58.835+0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
